---
title: "Guiné-Bissau"
output-file: "guinea-bissau"
iso: "GNB"
execute:
  echo: false
  warning: false
format:
  snapshot-pt-typst: default
---

```{r}
#| include: false
devtools::load_all(".")
knitr::opts_chunk$set(dev = "svglite")
code <- rmarkdown::metadata$iso
i <- 1
j <- 0
```

```{=typst}
#header(name: "I. MIGRAÇÃO")
```

```{=typst}
`r caption_stocks_pt(code)`
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.75
#| message: false

snap_plot("stocks", code, basesize = basesize, font = font, lang = "pt") |> 
  plot_label(i, span = 1, h = .15 / 2.75)
i <- i + 1
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.25
#| message: false

snap_plot("nats", code, basesize = basesize, font = font, lang = "pt") |> 
  plot_label(i, span = 1, h = .15 / 2.25)
i <- i + 1
```

```{=typst}
///////////////////////////////////////////////////////////////////// PAGE 2 ⬇️
#pagebreak()
```

```{=typst}
#caption[`r caption_migpyr_pt(code)`]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.50
#| message: false

snap_plot("migpyr", code, basesize = basesize, font = font, lang = "pt") |> 
  plot_label(i, span = 1, h = .15 / 2.50)
i <- i + 1
```

```{=typst}
#caption[`r caption_nmig_pt(code)`]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.50
#| message: false

cowplot::plot_grid(
  snap_plot("nmig", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i, h = .15 / 2.50),
  snap_plot("nmigmap", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 1, h = .15 / 2.50)
)
i <- i + 2
```

```{=typst}
`r caption_idp_pt(code)`
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.25
#| message: false

snap_plot("idp", code, basesize = basesize, font = font, lang = "pt") |> 
  plot_label(i, span = 1, h = .15 / 2.25)
i <- i + 1
```

```{=typst}
///////////////////////////////////////////////////////////////////// PAGE 3 ⬇️
#pagebreak()
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.75
#| message: false

cowplot::plot_grid(
  snap_plot("idpmap", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i, h = .15 / 2.75),
  snap_plot("idcause", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 1, h = .15 / 2.75)
)
i <- i + 2
```

```{=typst}
#caption[`r caption_mmp_pt(code)`]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.50
#| message: false

cowplot::plot_grid(
  snap_plot("mmp", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i, h = .15 / 2.50),
  snap_plot("mmpmap", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 1, h = .15 / 2.50)
)
i <- i + 2
```

```{=typst}
#caption[
`r caption_refug_orig_pt(code)`
#colbreak()
`r caption_refug_host_pt(code)`
]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.75
#| message: false

snap_plot("refug", code, basesize = basesize, font = font, lang = "pt") |> 
  plot_label(i, span = 1, h = .15 / 2.75)
i <- i + 1
```

```{=typst}
///////////////////////////////////////////////////////////////////// PAGE 4 ⬇️
#pagebreak()
```

```{=typst}
#caption[
`r caption_remin_pt(code)`
`r caption_remout_pt(code)`
#colbreak()
`r caption_fdiin_pt(code)`
`r caption_fdiout_pt(code)`
]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.25
#| message: false

cowplot::plot_grid(
  snap_plot("remt", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i, h = .15 / 2.25),
  snap_plot("fdi", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 1, h = .15 / 2.25)
)
i <- i + 2
```

```{=typst}
#header(
  name: "II. DEMOGRAFIA E ECONOMIA",
  note: "Os dados nesta secção referem-se à população geral da `r gdidata::countryname(rmarkdown::metadata$iso, to = 'name_text')` (ou seja, população migrante e não migrante)."
)
```

```{=typst}
#caption(ncol: 3)[
`r caption_pop_pt(code)`
#colbreak()
`r caption_birth_pt(code)`
#colbreak()
`r caption_depend_pt(code)`
]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.18
#| message: false

cowplot::plot_grid(
  snap_plot("pop", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i, span = 3, h = .15 / 2.18),
  snap_plot("birth", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 1, span = 3, h = .15 / 2.18),
  snap_plot("depend", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 2, span = 3, h = .15 / 2.18),
  nrow = 1
)
i <- i + 3
```

```{=typst}
#caption(ncol: 3)[
`r caption_income_pt(code)`
#colbreak()
`r caption_unem_pt(code)`
#colbreak()
`r caption_inf_pt(code)`
]
```

```{r}
#| fig-width: 6.7
#| fig-height: 2.18
#| message: false

cowplot::plot_grid(
  snap_plot("income", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i, span = 3, h = .15 / 2.18),
  snap_plot("unem", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 1, span = 3, h = .15 / 2.18),
  snap_plot("inf", code, basesize = basesize, font = font, lang = "pt") |> 
    plot_label(i + 2, span = 3, h = .15 / 2.18),
  nrow = 1
)
i <- i + 3
```
